# --------------------------------------------------------
# X-Decoder -- Generalized Decoding for Pixel, Image, and Language
# Copyright (c) 2022 Microsoft
# Licensed under The MIT License [see LICENSE for details]
# Written by Xueyan Zou (xueyan@cs.wisc.edu)
# --------------------------------------------------------
##################
# Task settings
##################
PIPELINE: HDecoderPipeline
TRAINER: hdecoder
SAVE_DIR: 'data/output_large/test'
base_path: "./"
WANDB: false
AUX_LOSS: true

# Resume Logistic
RESUME: false
WEIGHT: false
RESET_DATA_LOADER: false
RESUME_FROM: ''
PYLEARN_MODEL: '' # model resume when evaluation
DONT_LOAD_MODEL: true

# Logging and Debug
LOG_EVERY: 10
FIND_UNUSED_PARAMETERS: false

# Speed up training
FP16: false
PORT: '36873'
# misc
LOADER:
  JOINT: True
  KEY_DATASET: 'coco'
##################
# Task settings
##################
VERBOSE: true
MODEL:
  NAME: hoi_model
  HEAD: hoi_head
  TYPE: large
  MASK_ON: false
  KEYPOINT_ON: false
  LOAD_PROPOSALS: false
  DIM_PROJ: 512
  BACKBONE_DIM: 2048
  BACKBONE:
    NAME: focal
    PRETRAINED: ''
    LOAD_PRETRAINED: false
    FOCAL:
      PRETRAIN_IMG_SIZE: 224
      PATCH_SIZE: 4
      EMBED_DIM: 192
      DEPTHS: [2, 2, 18, 2]
      FOCAL_LEVELS: [4, 4, 4, 4]
      FOCAL_WINDOWS: [3, 3, 3, 3]
      DROP_PATH_RATE: 0.3
      MLP_RATIO: 4.0
      DROP_RATE: 0.0
      PATCH_NORM: True
      USE_CONV_EMBED: True
      SCALING_MODULATOR: True
      USE_CHECKPOINT: False
      USE_POSTLN: true
      USE_POSTLN_IN_MODULATION: false
      USE_LAYERSCALE: True
      OUT_FEATURES: ["res2", "res3", "res4", "res5"]
      OUT_INDICES: [0, 1, 2, 3]
  ENCODER:
    NAME: transformer_encoder_hoi
    IGNORE_VALUE: 255
    NUM_CLASSES: 133
    LOSS_WEIGHT: 1.0
    CONVS_DIM: 512
    MASK_DIM: 512
    NORM: "GN"
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
    DEFORMABLE_TRANSFORMER_ENCODER_IN_FEATURES: ["res3", "res4", "res5"]
    COMMON_STRIDE: 4
    TRANSFORMER_ENC_LAYERS: 6
  DECODER:
    NAME: hdecoder
    MASK: True
    HIDDEN_DIM: 512
    NUM_OBJECT_QUERIES: 100
    NUM_OBJECT_CLASSES: 81
    NUM_VERB_CLASSES: 29
    NHEADS: 8
    DROPOUT: 0.1
    DIM_FEEDFORWARD: 2048
    PRE_NORM: False
    HOPD_DEC_LAYERS: 6
    INTERACTION_DEC_LAYERS: 6
    RETURN_INTERMEDIATE_DEC: True
    # matcher
    COST_OBJECT_CLASS: 1
    COST_VERB_CLASS: 1
    COST_BBOX: 2.5
    COST_GIOU: 1
    COST_MATCHING: 1
    # loss coefficients
    OBJ_LOSS_COEF: 1
    VERB_LOSS_COEF: 2
    BBOX_LOSS_COEF: 2.5
    GIOU_LOSS_COEF: 1
    MATCHING_LOSS_COEF: 1
    EOS_COEF: 0.1
    SIZE_DIVISIBILITY: 32
INPUT:
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
DATASETS:
  # open vocabulary segmentation evaluation.
  TRAIN: ["vcoco_train"]
  TEST: ["vcoco_val"]
  CLASS_CONCAT: false
  SIZE_DIVISIBILITY: 32
  PROPOSAL_FILES_TRAIN: []
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: False
  NUM_WORKERS: 1
  LOAD_PROPOSALS: False
  SAMPLER_TRAIN: "TrainingSampler"
  ASPECT_RATIO_GROUPING: False
# Detectron2 training config for optimizer and lr scheduler
SOLVER:
  BASE_LR: 0.0001
  STEPS: [0.88889, 0.96296]
  MAX_ITER: 1
  GAMMA: 0.1
  WARMUP_FACTOR: 1.0
  WARMUP_ITERS: 10
  WARMUP_METHOD: "linear"
  WEIGHT_DECAY: 0.05
  OPTIMIZER: "ADAMW"
  # LR_SCHEDULER_NAME: "WarmupMultiStepLR"
  # LR_SCHEDULER_NAME: "StepLR"
  #   LR_DROP: 60
  LR_SCHEDULER_NAME: "MultiStepLR"
  LR_STEP: [60, 80]
  LR_MULTIPLIER:
    backbone: 0.1
    encoder: 0.1
  WEIGHT_DECAY_NORM: 0.0
  WEIGHT_DECAY_EMBED: 0.0
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 5.0 # 0.01
    NORM_TYPE: 2.0
  AMP:
    ENABLED: True
  MAX_NUM_EPOCHS: 90 #50
  FIX_PARAM:
    "backbone": false
    "encoder": false

VCOCO:
  INPUT:
    MIN_SIZE_TRAIN: 800
    MAX_SIZE_TRAIN: 1333
    MIN_SIZE_TRAIN_SAMPLING: 'choice'
    MIN_SIZE_TEST: 800
    MAX_SIZE_TEST: 1333
    IMAGE_SIZE: 1024
    MIN_SCALE: 0.1
    MAX_SCALE: 2.0
    IGNORE_VALUE: 255
    COLOR_AUG_SSD: False
    SIZE_DIVISIBILITY: 32
    RANDOM_FLIP: "horizontal"
    MASK_FORMAT: "polygon"
    FORMAT: "RGB"
    PIXEL_MEAN: [123.675, 116.280, 103.530]
    PIXEL_STD: [58.395, 57.120, 57.375]
    CROP:
      ENABLED: True
    NUM_QUERIES: 100
    DATASET_MAPPER_NAME: "vcoco"
  DATALOADER:
    FILTER_EMPTY_ANNOTATIONS: False
    NUM_WORKERS: 0
    LOAD_PROPOSALS: False
    SAMPLER_TRAIN: "TrainingSampler"
    ASPECT_RATIO_GROUPING: False
  TEST:
    BATCH_SIZE_TOTAL: 2
  TRAIN:
    BATCH_SIZE_TOTAL: 2
    BATCH_SIZE_PER_GPU: 1

POSTPROCESS:
  OFFICIAL:
    USE: false
    "synario": 1